services:
  _defaults:
    autowire: true
    bind:
      $file: 'input_data.txt'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  MowersController\:
    resource: '../src/'

  MowersController\Infrastructure\Application\Application:
    public: true
    arguments: [!tagged_iterator command]